name: neuromedex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_auth: ^5.4.0
  google_fonts: 5.0.0
  cloud_firestore: ^5.6.12
  lottie: ^3.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/Calendar.json
    - assets/lottie/Pills.json
    - assets/lottie/Heart.json
    - assets/lottie/Reports.json
    - assets/lottie/Notification.json
    - assets/lottie/Profile.json
    - assets/lottie/Configuracion.json