// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ7lqtj10nGIfraBGS-_Sp37y6e88Tkeo',
    appId: '1:966717177489:web:f2ca45a942ee2af1544930',
    messagingSenderId: '966717177489',
    projectId: 'neuromedx-77c11',
    authDomain: 'neuromedx-77c11.firebaseapp.com',
    storageBucket: 'neuromedx-77c11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsu4LxEvf7cs9SuAu6nau75wa-3nr8YD8',
    appId: '1:966717177489:android:303482eb5e94eae1544930',
    messagingSenderId: '966717177489',
    projectId: 'neuromedx-77c11',
    storageBucket: 'neuromedx-77c11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJNszWPYoAGsx3uuGAkMJTO0g-QF8QVQM',
    appId: '1:966717177489:ios:221326f72566cbfe544930',
    messagingSenderId: '966717177489',
    projectId: 'neuromedx-77c11',
    storageBucket: 'neuromedx-77c11.firebasestorage.app',
    iosBundleId: 'com.example.neuromedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJNszWPYoAGsx3uuGAkMJTO0g-QF8QVQM',
    appId: '1:966717177489:ios:221326f72566cbfe544930',
    messagingSenderId: '966717177489',
    projectId: 'neuromedx-77c11',
    storageBucket: 'neuromedx-77c11.firebasestorage.app',
    iosBundleId: 'com.example.neuromedex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ7lqtj10nGIfraBGS-_Sp37y6e88Tkeo',
    appId: '1:966717177489:web:f4e3b6988a6f899c544930',
    messagingSenderId: '966717177489',
    projectId: 'neuromedx-77c11',
    authDomain: 'neuromedx-77c11.firebaseapp.com',
    storageBucket: 'neuromedx-77c11.firebasestorage.app',
  );
}
